/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sanqing.struts.action;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.sanqing.struts.form.DepartmentEditorForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-20-2008
 * 
 * XDoclet definition:
 * @struts.action path="/venderTypeEditor" name="venderTypeEditorForm" input="/form/vender/venderTypeEditor.jsp" scope="request" validate="true"
 */
public class DepartmentEditorAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		DepartmentEditorForm DepartmentEditorForm = (DepartmentEditorForm) form;// TODO Auto-generated method stub
		try{
			PrintWriter out = response.getWriter();
			try{
				String oper = request.getParameter("oper");
				com.sanqing.bll.BDepartment B_V = new com.sanqing.bll.BDepartment();
				if(oper.equals("add"))
				{
					B_V.DepartmentAdd(DepartmentEditorForm);
				}
				else if(oper.equals("edit"))
				{
					B_V.DepartmentEdit(DepartmentEditorForm);
				}
				else if(oper.equals("delete"))
				{
					B_V.DepartmentDelete(DepartmentEditorForm.getDepartmengtId());
				}
				out.print(B_V.DepartmentConConvertToHTMLTable());	
				
			}
			catch(Exception e){
				out.print(e.getMessage());
			}
		
		}catch(IOException e1){
			e1.printStackTrace();
		}
		return null;
	}
}