/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sanqing.struts.action;

import java.io.IOException;
import java.io.PrintWriter;
import java.util.Collection;
import java.util.Vector;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import HibernateDao.Employee;
import HibernateDao.Itemgeneral;

import com.sanqing.struts.form.ItemeditorForm;

public class ItemeditorAction extends Action {
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		ItemeditorForm itemeditorForm = (ItemeditorForm) form;// TODO Auto-generated method stub
		try{
			PrintWriter out = response.getWriter();
			try{
				String oper = request.getParameter("oper");
			  System.out.println("前台操作标志"+oper);
				com.sanqing.bll.BItemGeneral B_V = new com.sanqing.bll.BItemGeneral();
				if(("add").equals(oper))
				{
					HibernateDao.Itemgeneral TypeModel = new HibernateDao.Itemgeneral();
					TypeModel.setClasscode(new HibernateDao.ClasscodeDAO().findById(itemeditorForm.getProd_code()));
					TypeModel.setEmployeeByPoEmpId(new HibernateDao.EmployeeDAO().findById(itemeditorForm.getPo_emp_id()));
					TypeModel.setEmployeeBySaleEmpId(new HibernateDao.EmployeeDAO().findById(itemeditorForm.getSale_emp_id()));					
					TypeModel.setItemDesc(itemeditorForm.getItem_desc());
					TypeModel.setItemId(itemeditorForm.getItem_id());
					TypeModel.setSalePic(Long.parseLong(itemeditorForm.getSale_pic()));
					TypeModel.setStatus(itemeditorForm.getStatus());
					TypeModel.setUmmaster(new HibernateDao.UmmasterDAO().findById(itemeditorForm.getUm_id()));
					TypeModel.setWarehouseBywareid(new HibernateDao.WarehouseDAO().findById(itemeditorForm.getWareId()));
					TypeModel.setLocationBylocationid(new HibernateDao.LocationDAO().findById(itemeditorForm.getLocaId()));
					TypeModel.setVendermasterByvendid(new HibernateDao.VendermasterDAO().findById(itemeditorForm.getVendId()));
					TypeModel.setNumber(Integer.valueOf(itemeditorForm.getNumber()));
					TypeModel.setSafestroage(itemeditorForm.getSafestroage());
					TypeModel.setMaxstroage(itemeditorForm.getMaxstroage());
					B_V.Item_Add(TypeModel);
				}
				else if(oper.equals("edit"))
				{
					HibernateDao.Itemgeneral TypeModel = new HibernateDao.Itemgeneral();
					TypeModel.setClasscode(new HibernateDao.ClasscodeDAO().findById(itemeditorForm.getProd_code()));
					TypeModel.setEmployeeByPoEmpId(new HibernateDao.EmployeeDAO().findById(itemeditorForm.getPo_emp_id()));
					TypeModel.setEmployeeBySaleEmpId(new HibernateDao.EmployeeDAO().findById(itemeditorForm.getSale_emp_id()));
					TypeModel.setItemDesc(itemeditorForm.getItem_desc());
					TypeModel.setItemId(itemeditorForm.getItem_id());
					TypeModel.setSalePic(Long.parseLong(itemeditorForm.getSale_pic()));
					TypeModel.setStatus(itemeditorForm.getStatus());
					TypeModel.setUmmaster(new HibernateDao.UmmasterDAO().findById(itemeditorForm.getUm_id()));
					TypeModel.setWarehouseBywareid(new HibernateDao.WarehouseDAO().findById(itemeditorForm.getWareId()));
					TypeModel.setLocationBylocationid(new HibernateDao.LocationDAO().findById(itemeditorForm.getLocaId()));
					TypeModel.setVendermasterByvendid(new HibernateDao.VendermasterDAO().findById(itemeditorForm.getVendId()));
					TypeModel.setNumber(Integer.valueOf(itemeditorForm.getNumber()));
					TypeModel.setSafestroage(itemeditorForm.getSafestroage());
					TypeModel.setMaxstroage(itemeditorForm.getMaxstroage());
					B_V.Item_Edit(TypeModel);
				}
				else if(oper.equals("lookup")){
					HibernateDao.ItemgeneralDAO D_ITEM = new HibernateDao.ItemgeneralDAO();
					Itemgeneral MyType = D_ITEM.findById(itemeditorForm.getItem_id());
					if (MyType==null) {
						out.print("flase");		
					}
					else{
					out.print(B_V.Item_ConvertModelToJson(request.getParameter("item_id")));
					}
					return null;
				}
				else if(oper.equals("delete"))
				{
					B_V.Item_Delete(itemeditorForm.getItem_id());
				}
				else if(oper.equals("model"))
				{
					out.print(B_V.Item_ConvertModelToJson(request.getParameter("item_id")));
					return null;
				}
				out.print(B_V.ItemsConvertToHTMLTable());	
			}catch(Exception e){
				out.print(e.getMessage());
			}
			
		}
		catch(IOException e1){
			e1.printStackTrace();
		}
		return null;
	}
}